# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main,crm-dev ]
  pull_request:
    branches: [ main, crm-dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  health-check-job:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{secrets.DEBUG}}
      SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github-actions
        ports: 
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{runner.os}}-pip-${{ hashFiles('**/requirements.txt')}}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check python version
        run: python --version
      - name: Install requirements
        run: pip install -r requirements.txt
#       - name: Check syntaxt
#         run: pycodestyle --statistics
      - name: Run Migration
        run: python manage.py migrate
      - name: Run Test
        run: python manage.py test

  Docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@V1
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tag: ${{secrets.DOCKERHUB_USERNAME}}/crm:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
